apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx   #In a Helm chart, {{ .Release.Name }} is a built-in Helm variable that represents the name of the release.
spec:
  replicas: {{ .Values.replicaCount }}    #({{ .Values }} placeholders) allow customization via values.yaml.
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
